"use client";
/* import type { Metadata } from "next"; */

import "slick-carousel/slick/slick.css"; // Slick Carousel styles
import "slick-carousel/slick/slick-theme.css"; // Slick Carousel theme styles

import localFont from "next/font/local";
import "./globals.css";
import AuthProviders from "@/services/AuthProviders";
import NavBar from "@/components/Shared/NavBar";

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

/* import { CartProvider } from "@/components/Home/Cart/CartData";
 */
import { usePathname } from "next/navigation";
import { CartProvider } from "@/components/Home/Cart/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/* export const metadata: Metadata = {
  title: "E-Com Zone",
  description: "Generated by create E-com Zone",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer />
        <AuthProviders>
          <CartProvider>
            {pathname !== "/" && <NavBar />}
            {children}
          </CartProvider>
        </AuthProviders>
      </body>
    </html>
  );
}
